{{- $tracingUrl := include "infra-sanity-service.tracingUrl" . -}}
{{- $metricsUrl := include "infra-sanity-service.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" (include "infra-sanity-service.fullname" .) }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  npm_config_cache: /tmp/
  {{- with .Values.configManagement }}
  CONFIG_NAME: {{ .name| quote }}
  CONFIG_VERSION: {{ .version | quote }}
  CONFIG_OFFLINE_MODE: {{ .offlineMode | quote }}
  CONFIG_SERVER_URL: {{ .serverUrl | quote }}
  {{- end -}}
{{- end }}
