apiVersion: v2
name: checkmate
description: A Helm chart for checkmate service
type: application
version: 1.0.1
appVersion: 1.0.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
